/**
 * Country code to display name mappings
 * Provides human-readable names for ISO 3166-1 alpha-3 country codes
 * Also includes custom FIFA codes for UK home nations (ENG, SCO, WAL, NIR)
 */

import { ValidCountry } from "../types";

export const NATIONALITY_DISPLAY_NAMES: Record<ValidCountry, string> = {
  // Major football nations (commonly used)
  ARG: "Argentina",
  AUS: "Australia",
  AUT: "Austria",
  BEL: "Belgium",
  BRA: "Brazil",
  CAN: "Canada",
  CHL: "Chile",
  CHN: "China",
  COL: "Colombia",
  HRV: "Croatia", // Alternative code for Croatia
  CZE: "Czech Republic",
  DNK: "Denmark",
  ENG: "England", // Custom FIFA code (not ISO 3166-1)
  SCO: "Scotland", // Custom FIFA code (not ISO 3166-1)
  WAL: "Wales", // Custom FIFA code (not ISO 3166-1)
  NIR: "Northern Ireland", // Custom FIFA code (not ISO 3166-1)
  FRA: "France",
  DEU: "Germany",
  GRC: "Greece",
  IND: "India",
  IRL: "Ireland",
  ITA: "Italy",
  JPN: "Japan",
  KOR: "South Korea",
  MEX: "Mexico",
  MAR: "Morocco",
  NLD: "Netherlands",
  NGA: "Nigeria",
  NOR: "Norway",
  POL: "Poland",
  PRT: "Portugal",
  ROU: "Romania",
  RUS: "Russia",
  SAU: "Saudi Arabia",
  SRB: "Serbia",
  ZAF: "South Africa",
  ESP: "Spain",
  SWE: "Sweden",
  CHE: "Switzerland",
  TUR: "Turkey",
  UKR: "Ukraine",
  URY: "Uruguay",
  USA: "United States",
  VEN: "Venezuela",

  // UEFA (Additional European countries)
  ALB: "Albania",
  AND: "Andorra",
  ARM: "Armenia",
  AZE: "Azerbaijan",
  BLR: "Belarus",
  BIH: "Bosnia and Herzegovina",
  BGR: "Bulgaria",
  CYP: "Cyprus",
  EST: "Estonia",
  FIN: "Finland",
  GEO: "Georgia",
  HUN: "Hungary",
  ISL: "Iceland",
  KAZ: "Kazakhstan",
  XKX: "Kosovo",
  LVA: "Latvia",
  LIE: "Liechtenstein",
  LTU: "Lithuania",
  LUX: "Luxembourg",
  MLT: "Malta",
  MDA: "Moldova",
  MCO: "Monaco",
  MNE: "Montenegro",
  MKD: "North Macedonia",
  SMR: "San Marino",
  SVK: "Slovakia",
  SVN: "Slovenia",
  VAT: "Vatican City",

  // CONMEBOL (Additional South American countries)
  BOL: "Bolivia",
  ECU: "Ecuador",
  GUF: "French Guiana",
  GUY: "Guyana",
  PRY: "Paraguay",
  PER: "Peru",
  SUR: "Suriname",

  // CONCACAF (Additional North/Central America & Caribbean)
  ATG: "Antigua and Barbuda",
  BHS: "Bahamas",
  BRB: "Barbados",
  BLZ: "Belize",
  CRI: "Costa Rica",
  CUB: "Cuba",
  DMA: "Dominica",
  DOM: "Dominican Republic",
  SLV: "El Salvador",
  GRD: "Grenada",
  GTM: "Guatemala",
  HTI: "Haiti",
  HND: "Honduras",
  JAM: "Jamaica",
  NIC: "Nicaragua",
  PAN: "Panama",
  KNA: "Saint Kitts and Nevis",
  LCA: "Saint Lucia",
  VCT: "Saint Vincent and the Grenadines",
  TTO: "Trinidad and Tobago",

  // CAF (Additional African countries)
  DZA: "Algeria",
  AGO: "Angola",
  BEN: "Benin",
  BWA: "Botswana",
  BFA: "Burkina Faso",
  BDI: "Burundi",
  CMR: "Cameroon",
  CPV: "Cape Verde",
  CAF: "Central African Republic",
  TCD: "Chad",
  COM: "Comoros",
  COG: "Congo",
  COD: "DR Congo",
  CIV: "Côte d'Ivoire",
  DJI: "Djibouti",
  EGY: "Egypt",
  GNQ: "Equatorial Guinea",
  ERI: "Eritrea",
  SWZ: "Eswatini",
  ETH: "Ethiopia",
  GAB: "Gabon",
  GMB: "Gambia",
  GHA: "Ghana",
  GIN: "Guinea",
  GNB: "Guinea-Bissau",
  KEN: "Kenya",
  LSO: "Lesotho",
  LBR: "Liberia",
  LBY: "Libya",
  MDG: "Madagascar",
  MWI: "Malawi",
  MLI: "Mali",
  MRT: "Mauritania",
  MUS: "Mauritius",
  MOZ: "Mozambique",
  NAM: "Namibia",
  NER: "Niger",
  RWA: "Rwanda",
  STP: "Sao Tome and Principe",
  SEN: "Senegal",
  SYC: "Seychelles",
  SLE: "Sierra Leone",
  SOM: "Somalia",
  SSD: "South Sudan",
  SDN: "Sudan",
  TZA: "Tanzania",
  TGO: "Togo",
  TUN: "Tunisia",
  UGA: "Uganda",
  ZMB: "Zambia",
  ZWE: "Zimbabwe",

  // AFC (Additional Asian countries)
  AFG: "Afghanistan",
  BHR: "Bahrain",
  BGD: "Bangladesh",
  BTN: "Bhutan",
  BRN: "Brunei",
  KHM: "Cambodia",
  PRK: "North Korea",
  HKG: "Hong Kong",
  IDN: "Indonesia",
  IRN: "Iran",
  IRQ: "Iraq",
  JOR: "Jordan",
  KWT: "Kuwait",
  KGZ: "Kyrgyzstan",
  LAO: "Laos",
  LBN: "Lebanon",
  MAC: "Macau",
  MYS: "Malaysia",
  MDV: "Maldives",
  MNG: "Mongolia",
  MMR: "Myanmar",
  NPL: "Nepal",
  OMN: "Oman",
  PAK: "Pakistan",
  PSE: "Palestine",
  PHL: "Philippines",
  QAT: "Qatar",
  SGP: "Singapore",
  LKA: "Sri Lanka",
  SYR: "Syria",
  TWN: "Taiwan",
  TJK: "Tajikistan",
  THA: "Thailand",
  TLS: "Timor-Leste",
  TKM: "Turkmenistan",
  ARE: "UAE",
  UZB: "Uzbekistan",
  VNM: "Vietnam",
  YEM: "Yemen",

  // OFC (Additional Oceanian countries)
  COK: "Cook Islands",
  FJI: "Fiji",
  NCL: "New Caledonia",
  NZL: "New Zealand",
  PNG: "Papua New Guinea",
  WSM: "Samoa",
  SLB: "Solomon Islands",
  TON: "Tonga",
  VUT: "Vanuatu",
} as const;
